### ISSUE TITLE
single-version-externally-managed not recognized

### ISSUE THREAD

**Issue by leguyader** [silx-kit/pyFAI#427] opened 2016-09-19 21:50 UTC
While installing pyFAI 0.12.0 on a local install of python3 on RedHat Entreprise Linux 6, I ran into the following error, with both setuptools 20.7.0 and 27.2.0:

```
me@here ~ % pip3 install --user pyFAI
Collecting pyFAI
  Using cached pyFAI-0.12.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in ./.local/lib/python3.5/site-packages (from pyFAI)
Requirement already satisfied (use --upgrade to upgrade): h5py in ./.local/lib/python3.5/site-packages (from pyFAI)
Requirement already satisfied (use --upgrade to upgrade): fabio in ./.local/lib/python3.5/site-packages (from pyFAI)
Requirement already satisfied (use --upgrade to upgrade): matplotlib in ./.local/lib/python3.5/site-packages (from pyFAI)
Requirement already satisfied (use --upgrade to upgrade): scipy in ./.local/lib/python3.5/site-packages (from pyFAI)
Requirement already satisfied (use --upgrade to upgrade): six in ./.local/lib/python3.5/site-packages (from h5py->pyFAI)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./.local/lib/python3.5/site-packages (from matplotlib->pyFAI)
Requirement already satisfied (use --upgrade to upgrade): pytz in ./.local/lib/python3.5/site-packages (from matplotlib->pyFAI)
Requirement already satisfied (use --upgrade to upgrade): cycler in ./.local/lib/python3.5/site-packages (from matplotlib->pyFAI)
Requirement already satisfied (use --upgrade to upgrade): pyparsing!=2.0.4,>=1.5.6 in ./.local/lib/python3.5/site-packages (from matplotlib->pyFAI)
Installing collected packages: pyFAI
  Running setup.py install for pyFAI ... error
    Complete output from command /u/xl/me/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4f64kv0q/pyFAI/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mweqrne5-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "/u/xl/me/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4f64kv0q/pyFAI/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mweqrne5-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-4f64kv0q/pyFAI/
```

Using egg instead of wheel solved the problem for now:

```
pip3 install --egg --user pyFAI
```

**Comment by kif** [comment] 2016-09-20 07:01
Dear Loïc, 

Thanks for the feed-back. The error you reported is indeed related to the packaging system and we never met it before. Our main target being Debian-8 and upcoming. Using a locally built from source python under Linux is usually not a good idea due to binary extension incompatibility. There is a recent PEP on the subject:
https://www.python.org/dev/peps/pep-0513/

According to information found on the internet, the solution you found is one of the easiest workaround.

I know Valentin recently worked on setuptools incompatibilities, so maybe he fixed this in the development branch.

You can try the development version it with:

git clone https://github.com/silx-kit/pyFAI
cd pyFAI
pip3 install . --user 

once installed you should run the tests:
cd ~
ipython3
import pyFAI
pyFAI.tests()

Cheers,

Jérôme

**Comment by vallsv** [comment] 2016-09-20 07:26
Hi. I see that few time ago, but i dont really understand/remember how to fix it. I guess it is an inconsistency between packaging libraries and the python installed in the system. First you should be sure that all packaging tools are up-to-date.

BTW, first, and for our information, can you list the installed libraries
```
python3 --version
pip3 list
```

Then you can update your packaging tools.
```
pip3 install --upgrade pip setuptools
```

**Comment by leguyader** [comment] 2016-09-20 20:49
I tried again installing pyFAI 0.12 with pip and setuptools up to date and could reproduce the error. The list of installed libraries is attached here. [versions.txt](https://github.com/silx-kit/pyFAI/files/483543/versions.txt)

Then I tried to install pyFAI 0.13.0a0 from git and it worked. One of the test failed though. 
[devtest.txt](https://github.com/silx-kit/pyFAI/files/483552/devtest.txt)

For comparison I reinstalled pyFAI 0.12 with --egg and launched pyFAI.tests() which all passed.

Cheers.

**Comment by kif** [comment] 2016-09-21 05:52
On Tue, 20 Sep 2016 13:49:38 -0700
Loïc Le Guyader <notifications@github.com> wrote:

> I tried again installing pyFAI 0.12 with pip and setuptools up to date and could reproduce the error. The list of installed libraries is attached here. [versions.txt](https://github.com/silx-kit/pyFAI/files/483543/versions.txt)

thanks, we will investigate.
 
> Then I tried to install pyFAI 0.13.0a0 from git and it worked. One of the test failed though. 
> [devtest.txt](https://github.com/silx-kit/pyFAI/files/483552/devtest.txt)

Thanks for the feed-back. We did not spot this one.

> 
> For comparison I reinstalled pyFAI 0.12 with --egg and launched pyFAI.tests() which all passed.
> 
indeed, it is a new feature :)

**Comment by kif** [comment] 2016-09-21 07:09
I am compiling python3.5 to test ... and managed to reproduce the bug on python3.5.2
backports.shutil-get-terminal-size==1.0.0
cycler==0.10.0
dask==0.10.1
decorator==4.0.10
entrypoints==0.2.2
fabio==0.4.0
h5py==2.6.0
ipykernel==4.3.1
ipython==5.0.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.3.0
jupyter-console==5.0.0
jupyter-core==4.1.0
MarkupSafe==0.23
matplotlib==1.5.1
mistune==0.7.3
nbconvert==4.2.0
nbformat==4.0.1
networkx==1.11
notebook==4.2.1
numpy==1.11.1
pexpect==4.2.0
pickleshare==0.7.3
Pillow==3.3.0
prompt-toolkit==1.0.3
ptyprocess==0.5.1
Pygments==2.1.3
pyparsing==2.1.5
python-dateutil==2.5.3
pytz==2016.6.1
pyzmq==15.3.0
qtconsole==4.2.1
scikit-image==0.12.3
scipy==0.17.1
simplegeneric==0.8.1
six==1.10.0
terminado==0.6
toolz==0.8.0
tornado==4.4
traitlets==4.2.2
wcwidth==0.1.7
widgetsnbextension==1.2.6

**Comment by kif** [comment] 2016-09-21 07:39
Hi,

I managed to reproduce the bug, both using "pip install pyFAI" and "pip install ." in the sources of 0.12. The same procedure works for 0.13-dev but I don't know why. The bug you spotted is related to the "pyFAI-average" script. If you wish to use the python interface, you should not be affected. 

Cheers,

Jerome

**Comment by vallsv** [comment] 2016-09-21 11:57
I try to reproduce the problem with progressbar using Python 3.4.2 without success. Hope this PR fix the problem https://github.com/silx-kit/pyFAI/pull/431. I will test it tomorrow with Jerome.

Thanks a lot for the feed back.

**Comment by vallsv** [comment] 2018-02-06 10:33
Should be fixed now

**Closed by vallsv** 2018-02-06 10:33 UTC
