### ISSUE TITLE
[peak_picker] gui error with Mac

### ISSUE THREAD

**Issue by chiahaoliu** [silx-kit/pyFAI#682] opened 2017-09-07 14:50 UTC
When running the peak peak gui from ipython, following error will always encountered when it's run with Mac:

````
~/miniconda3/envs/bs_dev/lib/python3.6/site-packages/pyFAI/peak_picker.py in gui(self, log, maximize, pick)
    264             self.msp = self.fig.add_subplot(111)
    265             toolbar = self.fig.canvas.toolbar
--> 266             toolbar.addSeparator()
    267
    268             a = toolbar.addAction('Opts', self.on_option_clicked)

AttributeError: 'NavigationToolbar2Mac' object has no attribute 'addSeparator'
````

It seems to come from ``matplotlib`` but I am not 100% sure.

package information:
````
matplotlib                2.0.2               np112py36_0
python                    3.6.1                         2
pyfai                     0.14.0              np112py36_0
````

**Comment by vallsv** [comment] 2017-09-07 15:27
Hi. Which Qt version do you use?

**Comment by vallsv** [comment] 2017-09-07 15:31
Ok, then i think it is not a Qt binding, but a pure Mac OS X GUI. Then the way we use is can't work. Can you install PyQt5?

**Comment by vallsv** [comment] 2017-09-07 15:51
It would be very useful if you show use the result of this commands from your python shell:
```
import pyFAI.gui.qt
import pyFAI.gui.matplotlib
import matplotlib
pyFAI.gui.qt.BINDING
[(k, v) for k, v in matplotlib.rcParams.items() if 'backend' in k]
```

**Comment by chiahaoliu** [comment] 2017-09-07 16:59
Thanks for the reply. Here is the output based on the suggested code:

````
[('backend', 'Qt5Agg'),
 ('backend_fallback', True),
 ('backend.qt4', 'PyQt4'),
 ('backend.qt5', 'PyQt5')]
````

And that's the conda package info

````
pyqt                      5.6.0                    py36_2
````

**Comment by vallsv** [comment] 2017-09-08 07:12
Then the problem is on our side.

We will release a new version of pyFAI next week.
But if you don't have time to wait, you can call this before calling anything else, and it should fix your issue.
```
import pyFAI.gui.matplotlib
```

**Comment by vallsv** [comment] 2017-09-08 08:08
BTW do you use the module with your own program? or does it occurs when you use pyFAI-calib.

In the first case you have to configure matplotlib by yourself to use Qt. We can fix our code to avoid exception, but it will disable some features.

**Comment by vallsv** [comment] 2017-09-08 08:51
> We can fix our code to avoid exception, but it will disable some features.

I was wrong, we can't remove this features, that's needed for the application. Then you have to use Qt.

**Comment by chiahaoliu** [comment] 2017-09-10 19:45
I used this module in my own problem, not with ``pyFAI-calib``.  It's glad to hear this is going to next release!

Regarding the fix, ``import pyFAI.gui.matplotlib``,  it doesn't seem to solve the problem. (I already put it at the top import). Would it be something more subtle? Thanks.

**Comment by CJ-Wright** [comment] 2017-09-10 20:08
Would it be possible to not use Qt bindings? It seems that native mpl has gotten better at handling interactive figures. This would also allow calibrate to work within a Jupyter notebook.

**Comment by kif** [comment] 2017-09-11 07:34
On Sun, 10 Sep 2017 20:08:10 +0000 (UTC)
"Christopher J. Wright" <notifications@github.com> wrote:

> Would it be possible to not use Qt bindings? It seems that native mpl
> has gotten better at handling interactive figures. This would also
> allow calibrate to work within a Jupyter notebook.

Hi Christopher,

The problem is the interaction with jupyter notebooks. 
Matplotlib is a plotting library (it is great a doing it's job), but
the interaction offered with the graph is limited (see the limits of
pyFAI calib).

We need to find a plotting interface which works with jupyter: plot.ly,
bokeh are examples but the problem is then how to manage 16 mpix images.

This topic should be best discussed in the pyFAI mailing list.

Cheers,
-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vallsv** [comment] 2017-09-11 07:59
>  It's glad to hear this is going to next release!

While people use it, it will stay there, i guess. The idea is not to break everything.

> Regarding the fix, import `pyFAI.gui.matplotlib`, it doesn't seem to solve the problem. (I already put it at the top import). Would it be something more subtle? Thanks.

No there is not.
But you have to import it before matplotlib, else matplotlib may have already configure the backend for you.
Is you module is the main module, or it is used by a bigger application?

You tried it previously with the script i asked you to check, and it was working. It's basically the same.

**Comment by vallsv** [comment] 2017-09-14 08:10
Then i close this issue, while it looks to be outside for our scope.
But we still can help you with your code, there is no problem.

**Closed by vallsv** 2017-09-14 08:10 UTC
Labels: wontfix
