### ISSUE TITLE
[gui] Error in the console

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#984] opened 2018-10-31 10:11 UTC
Hello, I try to profile calib2, And I get this message in the console.

```
picca@diffabs6:~/pyFAI/doc/source/usage/tutorial/Soleil$ python -m cProfile /usr/lib/python2.7/dist-packages/pyFAI/app/calib2.py
ERROR:silx.gui.plot.tools.PositionInfo:Error while converting coordinates (311.000000, 429.000000)with converter 'Value'
ERROR:silx.gui.plot.tools.PositionInfo:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/tools/PositionInfo.py", line 272, in _updateStatusBar
    value = func(xData, yData)
  File "/usr/lib/python2.7/dist-packages/pyFAI/gui/calibration/MaskTask.py", line 221, in __getImageValue
    image = self.__plot.getImage("image")
AttributeError: 'MaskTask' object has no attribute '_MaskTask__plot'
```

cheers

**Comment by vallsv** [comment] 2018-11-21 13:50
BTW the GUI was designed with Python 3, and not tested with Python 2, then maybe using Python 3 could help.

But i am trying to reproduce the problem. If we can fix it, it's fine.

**Comment by vallsv** [comment] 2018-11-21 13:59
Hi. I try on debian8 python2 without any problems.

I am pretty sure the issue is relative of an user interaction and have nothing to do with `cProfile`. Then if you remember how you do it, it could be useful.

**Comment by vallsv** [comment] 2018-12-14 18:13
Well, `__plot` is the very first thing created on this class. Then i have no idea. I close it.

**Comment by vallsv** [comment] 2018-12-14 18:14
I mean, now on the master it is the very first thing, maybe this fixed the issue.

**Comment by vallsv** [comment] 2018-12-18 15:41
That's a crazy bug. Still there.

**Comment by vallsv** [comment] 2018-12-18 15:42
I suspect unluck on startup mouse location
```
ERROR:silx.gui.plot.tools.PositionInfo:Traceback (most recent call last):
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/tools/PositionInfo.py", line 272, in _updateStatusBar
    value = func(xData, yData)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/calibration/MaskTask.py", line 252, in __getImageValue
    image = self.__plot.getImage("image")
AttributeError: 'MaskTask' object has no attribute '_MaskTask__plot'
```

**Closed** 2018-12-18 16:45 UTC
Labels: bug
