### ISSUE TITLE
numpy.float64' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#679] opened 2017-09-07 12:09 UTC
Hello, when I try to click on the compute image intensity distribution, I get this error 0.5.0
```
ERROR:pyFAI-calib2.UNCAUGHT:'numpy.float64' object cannot be interpreted as an index
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/PlotActions.py", line 1199, in _triggered
    self.computeIntensityDistribution()
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/PlotActions.py", line 1243, in computeIntensityDistribution
    histogram = Histogramnd(data, n_bins=nbins, histo_range=data_range)
  File "/usr/lib/python2.7/dist-packages/silx/math/histogram.py", line 251, in __init__
    wh_dtype=self.__wh_dtype)
  File "silx/math/histogramnd/chistogramnd.pyx", line 286, in chistogramnd.chistogramnd (silx/math/histogramnd/chistogramnd.c:4784)
TypeError: 'numpy.float64' object cannot be interpreted as an index
```

**Comment by vallsv** [comment] 2017-09-07 13:33
The number of bins have to be an integer, but is provided as a float. I still have to check why.

**Comment by vallsv** [comment] 2017-09-07 13:35
Ok, i catch it. Thanks for the feedback.

**Comment by picca** [comment] 2017-09-07 13:43
haskell is your friend ;)

**Comment by vallsv** [comment] 2017-09-07 13:54
Which version of `numpy` are you using? It is still strange.

**Comment by picca** [comment] 2017-09-07 14:07
The one from stretch 

ii  python-numpy                              1:1.12.1-3

**Comment by picca** [comment] 2017-09-07 14:08
It is true that numpy 1.12 is quite strict with the index type.

**Comment by vallsv** [comment] 2017-09-07 14:34
Can you send to me your image? I would like to check pixel intensity?

**Comment by vallsv** [comment] 2017-09-07 15:23
Thanks for the image. But i can't reproduce it...

Where did you exactly clicked? To display the distribution of your input image only?
Can you show us the output of `pip list`?

**Comment by kif** [comment] 2018-01-30 08:31
addressed in silx

**Closed by kif** 2018-01-30 08:31 UTC
